# Site settings
title: Jason Gilmour
email: hello@jasongilmour.co.uk
description: Jason Gilmour is a Senior Designer working in Edinburgh with a focus on UX, strategy, and business. Currently open to exploring opportunities in Canada.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jasongilmour.co.uk" # the base hostname & protocol for your site
twitter_username: jasongilmour94

# Build settings
# markdown: kramdown
sass:
  style: expanded
permalink: :categories/:title/

# plugins:
#   - jekyll-sitemap
